### ISSUE TITLE
Transport endpoint is not connected

### ISSUE THREAD

**Issue by Kitoko86** [lucasvr/demuxfs#1] opened 2020-06-24 13:18 UTC
Hi,

When I want to mount a recorded MPEG ts file stream as a filesystem on Ubuntu 20.04 with the following command:

`$ demuxfs -f -o standard=DVB -o backend=filesrc -o filesrc=/home/gael/Bureau/1072_522_H_DVBT /home/gael/Bureau/Mount/DemuxFS`

I encounter the error "The transport endpoint is not connected". What can I do to solve this?

**Comment by lucasvr** [comment] 2020-06-24 13:25
Hello there. The error suggests that `/home/gael/Bureau/Mount/DemuxFS` is already mounted, and that the previous call to demuxfs crashed. You can run `fusermount -u /home/gael/Bureau/Mount/DemuxFS` to unmount it prior to calling `demuxfs` again.

Please let me know if you can reproduce the crash so I can look into fixing it.

**Comment by Kitoko86** [comment] 2020-06-24 13:29
Thanks for your answer. I already tried that but without success. Here is the [link](https://drive.google.com/file/d/1kyz_qaP7YoGCrLcps7IKzwiH6TX0ry1g/view?usp=sharing) to the MPEG stream for you. This way, you can test on your side.

**Comment by lucasvr** [comment] 2020-06-24 13:50
Thanks for the file, I can reproduce the crash. I'll work on a fix for this one.

**Comment by lucasvr** [comment] 2020-06-24 14:08
Checked-in a fix on d072f544e381962471a305e139a46378daa65068. Please test and let me know if it works for you.

**Comment by Kitoko86** [comment] 2020-06-24 14:22
It seems working. Congratulations! I do more in depth testing and I'll close the issue if all goes well.

**Comment by lucasvr** [comment] 2020-06-24 14:41
I'll close it now since this very issue is gone. Please reopen (or create a new one) if you spot a different crash or unexpected behavior. Thanks!

**Closed as completed by lucasvr** 2020-06-24 14:41 UTC
